config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true, length: { maximum: Settings.validates.length.maximum.name }

  validates :email, presence: true, length: { maximum: Settings.validates.length.maximum.email },
                    format: { with: Settings.valid_email_regex },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length:  { minimum: Settings.validates.length.minimum.password,
                                                  maximum: Settings.validates.length.maximum.password,
                                                }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @users = User.find_by(id: params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Create account sucessfully'
      redirect_to users_path
    else
      flash[:succerss] = 'Create account failed'
      render 'new'
    end
  end
end

# PATCH/PUT /users/1 or /users/1.json
def update
  if @user.update(user_params)
    flash[:success] = 'User was successfully updated'
    redirect_to @user
  else
    render 'edit'
  end
end

# DELETE /users/1 or /users/1.json
def destroy
  @user.destroy
  flash[:success] = 'User was successfully updated'
  redirect_to users_url
end

private
# Only allow a list of trusted parameters through.
def user_params
  params.require(:user).permit :name, :email, :password, :password_confirmation
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>RailsDockerApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

            <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
                <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <section class="content" style="min-height: auto;">
        <% flash.each do |key, value| %>
            <div class="row">
                <div class="alert alert-<%= key %>">
                    <%= value %>
                </div>
            </div>
            <% end %>
    </section>
    <%= yield %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <ul>
        <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
     <%= form_for(@user) do |f| %>
       <%= render 'shared/error_messages', object: f.object %>

       <%= f.label :name %>
       <%= f.text_field :name, class: 'form-control' %>

       <%= f.label :email %>
       <%= f.email_field :email, class: 'form-control' %>

       <%= f.label :password %>
       <%= f.password_field :password, class: 'form-control' %>

       <%= f.label :password_confirmation, "Confirmation" %>
       <%= f.password_field :password_confirmation, class: 'form-control' %>

       <%= f.submit "Create my account", class: "btn btn-primary" %>
     <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <div class="text-left">
        <label><%= @user.name %></label>
      </div>
      <%= link_to "Logout", logout_path, method: :delete %>
    </div>
  </div>
</div>